/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bilboka.messagebot

import bilboka.core.book.domain.FuelRecord
import bilboka.core.vehicle.Vehicle
import bilboka.core.vehicle.VehicleNotFoundException
import io.mockk.confirmVerified
import io.mockk.every
import io.mockk.junit5.MockKExtension
import io.mockk.verify
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(MockKExtension::class)
class FuelRecordAdderTest : AbstractMessageBotTest() {

    @Test
    fun sendAddFuelRequest_callsAddFuelExecutor() {
        every { carBookExecutor.addRecordToVehicle(any(), any()) } returns Vehicle("testbil")

        messagebot.processMessage("Drivstoff testbil 30l 300kr", senderID)

        verify {
            botMessenger.sendMessage(
                "Registrert tanking av testbil, 30.0 liter for 300.0 kr, 10.0 kr/l",
                senderID
            )
        }
        verify { carBookExecutor.addRecordToVehicle(ofType(FuelRecord::class), "testbil") }
        confirmVerified(botMessenger, carBookExecutor)
    }

    @Test
    @Disabled // TODO
    fun sendAddFuelRequestDifferentCase_callsAddFuelExecutor() {
        every { carBookExecutor.addRecordToVehicle(any(), any()) } returns Vehicle("en testbil")

        messagebot.processMessage("fylt en testbil 30.2 L 300.60 Kr", senderID)

        verify {
            botMessenger.sendMessage(
                "Registrert tanking av en testbil, 30.2 liter for 300.6 kr, 9.953642384105962 kr/l,",
                senderID
            )
        }
        verify { carBookExecutor.addRecordToVehicle(ofType(FuelRecord::class), "en testbil") }
        confirmVerified(botMessenger, carBookExecutor)
    }

    @Test
    @Disabled // TODO
    fun sendAddFuelRequestDifferentCaseWithComma_callsAddFuelExecutor() {
        every { carBookExecutor.addRecordToVehicle(any(), any()) } returns Vehicle("XC 70")

        messagebot.processMessage("Hei drivstoff XC 70 30,44 l 3000,07 kr.. :D", senderID)

        verify {
            botMessenger.sendMessage(
                "Registrert tanking av XC 70, 30.44 liter for 3000.07, 98.55683311432325 kr/l,",
                senderID
            )
        }
        verify { carBookExecutor.addRecordToVehicle(ofType(FuelRecord::class), "XC 70") }
        confirmVerified(botMessenger, carBookExecutor)
    }

    @Test
    fun sendAddFuelRequestForUnknownCar_answersCarUnknown() {
        every { carBookExecutor.addRecordToVehicle(any(), any()) } throws VehicleNotFoundException("Hei!")

        messagebot.processMessage("Drivstoff testbil 30l 300kr", senderID)

        verify { botMessenger.sendMessage("Kjenner ikke til bil testbil", senderID) }
        confirmVerified(botMessenger)
    }
}
