/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bilboka.messagebot

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class MessageBotTest {
    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = MessageBot()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
