/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bilboka.messenger.integration

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class MessengerIntegrationTest {
    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = MessengerIntegration()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
