/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bilboka.messenger.integration

class MessengerIntegration {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
